apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ruby-app
  description: An example of a ruby application.
  annotations:
    package-deps/gem: "file:/Users/sas/Code/github.com/voodooGQ/backstage-plugins/examples/repos/ruby/Gemfile"
spec:
  type: app
  owner: guests
  lifecycle: experimental

